version: '3'
services:
  Nodo_1:
    image: nodo
    build:
      context: ./Nodo
      dockerfile: ./Dockerfile
    ports:
      - 1500:5000
    networks:
      - clus_net
    volumes:
      -  /home/morin/Escritorio/A1_Bully/Files/:/app/data/
    command: python /app/nodo_1.py 1 1500 1501,1502,1503,1504,1505 0
  
  Nodo_2:
    image: nodo
    build:
      context: ./Nodo
      dockerfile: ./Dockerfile
    ports:
      - 1501:5000
    networks:
      - clus_net
    volumes:
      -  /home/morin/Escritorio/A1_Bully/Files/:/app/data/
    command: python /app/nodo_1.py 2 1501 1500,1502,1503,1504,1505 0

  Nodo_3:
    image: nodo
    build:
      context: ./Nodo
      dockerfile: ./Dockerfile
    ports:
      - 1502:5000
    networks:
      - clus_net
    volumes:
      -  /home/morin/Escritorio/A1_Bully/Files/:/app/data/
    command: python /app/nodo_1.py 3 1502 1500,1501,1503,1504,1505 0
    
  Nodo_4:
    image: nodo
    build:
      context: ./Nodo
      dockerfile: ./Dockerfile
    ports:
      - 1503:5000
    networks:
      - clus_net
    volumes:
      -  /home/morin/Escritorio/A1_Bully/Files/:/app/data/
    command: python /app/nodo_1.py 4 1503 1500,1501,1502,1504,1505 0
    
  Nodo_5:
    image: nodo
    build:
      context: ./Nodo
      dockerfile: ./Dockerfile
    ports:
      - 1504:5000
    networks:
      - clus_net
    volumes:
      -  /home/morin/Escritorio/A1_Bully/Files/:/app/data/
    command: python /app/nodo_1.py 5 1504 1500,1501,1502,1503,1505 0
  
  Nodo_6:
    image: nodo
    build:
      context: ./Nodo
      dockerfile: ./Dockerfile
    ports:
      - 1505:5000
    networks:
      - clus_net
    volumes:
      -  /home/morin/Escritorio/A1_Bully/Files/:/app/data/
    command: python /app/nodo_1.py 6 1505 1500,1501,1502,1503,1504 1

networks:
  clus_net:
